
	--RENZU ITEMS
	['nitro'] 				 	 = {['name'] = 'nitro', 			  	  		['label'] = 'Nitro', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'nitrous.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},


	['turbo_racing'] 				 	 = {['name'] = 'turbo_racing', 			  	  		['label'] = 'Turbo Racing', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_racing.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['turboracing'] 				 	 = {['name'] = 'turboracing', 			  	  		['label'] = 'Turbo Racing Sound', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_racing.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Turbo Racing Sound! :D'},

	['turbo_sports'] 				 	 = {['name'] = 'turbo_sports', 			  	  		['label'] = 'Turbo Sports', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_sports.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['turbosports'] 				 	 = {['name'] = 'turbosports', 			  	  		['label'] = 'Turbo Sports Sound', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_sports.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Turbo Sports Sound! :D'},

	['turbo_street'] 				 	 = {['name'] = 'turbo_street', 			  	  		['label'] = 'Turbo Street', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['turbostreet'] 				 	 = {['name'] = 'turbostreet', 			  	  		['label'] = 'Turbo Street Sound', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Turbo Street Sound! :D'},

	['street_tirekit'] 				 	 = {['name'] = 'street_tirekit', 			  	  		['label'] = 'Street Tire Kit', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'street_tirekit.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Street Tire Kit! :D'},
	['sports_tirekit'] 				 	 = {['name'] = 'sports_tirekit', 			  	  		['label'] = 'Sports Tire Kit', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'sports_tirekit.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Sports Tire Kit! :D'},
	['racing_tirekit'] 				 	 = {['name'] = 'racing_tirekit', 			  	  		['label'] = 'Racing Tires Kit', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'racing_tirekit.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Racing Tires Kit! :D'},
	['drag_tirekit'] 				 	 = {['name'] = 'drag_tirekit', 			  	  		['label'] = 'Drag Tires Kit', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'drag_tirekit.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Drag Tires Kit! :D'},
	
	['head_brace'] 			 		 = {['name'] = 'head_brace', 						['label'] = 'Head Brace', 					['weight'] = 0, 		['type'] = 'item', 		['image'] = 'head_bandage.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,    ['combinable'] = nil,   ['description'] = 'A Head Brace works every time'},
	['leg_bandage'] 			 		 = {['name'] = 'leg_bandage', 						['label'] = 'Leg Bandage', 					['weight'] = 0, 		['type'] = 'item', 		['image'] = 'leg_bandage.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,    ['combinable'] = nil,   ['description'] = 'A Leg Bandage works every time'},
	['arm_bandage'] 			 		 = {['name'] = 'arm_bandage', 						['label'] = 'Arm Bandage', 					['weight'] = 0, 		['type'] = 'item', 		['image'] = 'arm_bandage.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,    ['combinable'] = nil,   ['description'] = 'A Arm Bandage works every time'},
	['body_bandage'] 			 		 = {['name'] = 'body_bandage', 						['label'] = 'Body Bandage', 					['weight'] = 0, 		['type'] = 'item', 		['image'] = 'chest_bandage.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,    ['combinable'] = nil,   ['description'] = 'A Body Bandage works every time'},

	['b16b'] 				 	 = {['name'] = 'b16b', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['rb26dett'] 				 	 = {['name'] = 'rb26dett', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['supra2jzgtett'] 				 	 = {['name'] = 'supra2jzgtett', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['rx713b'] 				 	 = {['name'] = 'rx713b', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['musv8'] 				 	 = {['name'] = 'musv8', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['r488sound'] 				 	 = {['name'] = 'r488sound', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['apollosv8'] 				 	 = {['name'] = 'apollosv8', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['avesvv12'] 				 	 = {['name'] = 'avesvv12', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['c6v8sound'] 				 	 = {['name'] = 'c6v8sound', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['diablov12'] 				 	 = {['name'] = 'diablov12', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['f40v8'] 				 	 = {['name'] = 'f40v8', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['f50v12'] 				 	 = {['name'] = 'f50v12', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['ferrarif12'] 				 	 = {['name'] = 'ferrarif12', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['gtaspanov10'] 				 	 = {['name'] = 'gtaspanov10', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['k20a'] 				 	 = {['name'] = 'k20a', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['r35sound'] 				 	 = {['name'] = 'r35sound', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['mclarenv8'] 				 	 = {['name'] = 'mclarenv8', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['murciev12'] 				 	 = {['name'] = 'murciev12', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['perfov10'] 				 	 = {['name'] = 'perfov10', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['sestov10'] 				 	 = {['name'] = 'sestov10', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['urusv8'] 				 	 = {['name'] = 'urusv8', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['veyronsound'] 				 	 = {['name'] = 'veyronsound', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['viperv10'] 				 	 = {['name'] = 'viperv10', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['gt3flat6'] 				 	 = {['name'] = 'gt3flat6', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['m158huayra'] 				 	 = {['name'] = 'm158huayra', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['m297zonda'] 				 	 = {['name'] = 'm297zonda', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},
	['p60b40'] 				 	 = {['name'] = 'p60b40', 			  	  		['label'] = 'ENGINE', 					['weight'] = 100, 		['type'] = 'item', 		['image'] = 'turbo_street.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'Speed up, gas pedal! :D'},

