fx_version 'cerulean'
game { 'gta5' }
name 'renzu_engine'
description 'Change Vehicle Engine Sound and Sync to all server One Sync/One Sync Infinity (included carsound pack from gta5mods)'
author 'renzu'
version '2.0'

lua54 'on'

shared_scripts {
	"config.lua"
}

server_scripts {
  '@mysql-async/lib/MySQL.lua',	
	"server.lua"
}
client_scripts {
	"client.lua",
}


files {
  'audioconfig/*.dat151',
  'audioconfig/*.dat151.nametable',
  'audioconfig/*.dat151.rel',
  'audioconfig/*.dat10.nametable',
  'audioconfig/*.dat10.rel',
  'audioconfig/*.dat10',  
  'audioconfig/*.dat54.nametable',
  'audioconfig/*.dat54.rel',
  'audioconfig/*.dat54',
  'audioconfig/*.dat',
  '*.json'
  'sfx/**/*.awc'
}


data_file 'AUDIO_GAMEDATA' 	'audioconfig/12vcummins_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/46fordmodular_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/53vortec_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/64powerstroke_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/488sound_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/apollosv8_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/argento_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/ariant_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/avesvv12_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/b58b30_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/bmws702_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/brabus850_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/c6v8sound_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/c30a_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/cw2019_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/demonv8_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/diablov12_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/dlcenginev10_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/elegyx_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/f40v8_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/f50v12_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/f136_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/ferrarif12_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/gresleyh_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/gt3flat6_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/gtaspanov10_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/hemisound_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/k20a_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/laferrarisound_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/lambov10_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/lfasound_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/m113k_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/m158huayra_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/m297zonda_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/majimalm_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/mclarenv8_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/mercm177_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/mercm279_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/monroec_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/murciev12_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/musv8_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/nfsv8_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/p60b40_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/perfov10_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/porschema2_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/predatorv8_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/r34sound_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/rb26dett_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/roger_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/rotary7_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/s85b50_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/s85b50b_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/sentinelsg4_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/sestov10_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/shonen_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/skart_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/stratumc_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/sultanrsv8_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/toysupmk4_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/urusv8_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/venenov12_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/viperv10_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/genx_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/trent1000_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/trent1000tss_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cfm562c5_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/jt3d3b_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/jt3d7_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/jt3c_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cfm565_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/iaev2500_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cfmleap1a_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/pw1100g_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/jt8d_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cfm563b_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cfm567b_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cfmleap1b_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/pt6a67d_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ct79b_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/pw150a_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/pw127m_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/io540_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/io360_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lf507_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/trent500_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/pw2000_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/rb211535_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cf650c_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cf650e_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cf680c_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/trentxwb97_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/tf34ge100a_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/pw200_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ge400_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/f119pw100_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/f404_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/olympus593_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/genx2b_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ge90115b_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/f20c_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/fd3sid_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s54b32_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/z33u2_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/bgw16_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/chevroletlt4_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/13b-rew_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/bmws55_game.dat'


data_file 'AUDIO_SOUNDDATA' 'audioconfig/12vcummins_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/46fordmodular_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/53vortec_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/64powerstroke_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/488sound_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/apollosv8_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/argento_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ariant_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/avesvv12_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/b58b30_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/bmws702_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/brabus850_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/c6v8sound_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/c30a_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cw2019_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/demonv8_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/diablov12_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/dlcenginev10_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/elegyx_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f40v8_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f50v12_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f136_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ferrarif12_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/gresleyh_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/gt3flat6_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/gtaspanov10_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/hemisound_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/k20a_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/laferrarisound_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lambov10_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lfasound_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/m113k_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/m158huayra_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/m297zonda_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/majimalm_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/mclarenv8_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/mercm177_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/mercm279_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/monroec_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/murciev12_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/musv8_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/nfsv8_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/p60b40_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/perfov10_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/porschema2_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/predatorv8_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/r34sound_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/rb26dett_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/roger_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/rotary7_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s85b50_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s85b50b_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/sentinelsg4_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/sestov10_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/shonen_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/skart_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/stratumc_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/sultanrsv8_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/toysupmk4_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/urusv8_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/venenov12_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/viperv10_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/genx_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/trent1000_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/trent1000tss_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cfm562c5_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/jt3d3b_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/jt3d7_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/jt3c_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cfm565_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/iaev2500_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cfmleap1a_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/pw1100g_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/jt8d_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cfm563b_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cfm567b_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cfmleap1b_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/pt6a67d_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ct79b_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/pw150a_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/pw127m_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/io540_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/io360_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lf507_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/trent500_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/pw2000_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/rb211535_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cf650c_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cf650e_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cf680c_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/trentxwb97_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/tf34ge100a_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/pw200_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ge400_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f119pw100_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f404_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/olympus593_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/genx2b_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ge90115b_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f20c_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/fd3sid_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s54b32_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/z33u2_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/bgw16_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/chevroletlt4_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/13b-rew_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/bmws55_sounds.dat'


data_file 'AUDIO_SYNTHDATA' 'audioconfig/c30a_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/f136_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/gresleyh_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/gt3flat6_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/k20a_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/m158huayra_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/m297zonda_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/monroec_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/rb26dett_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/shonen_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/stratumc_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/pt6a67d_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/ct79b_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/pw150a_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/pw127m_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/pw200_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/ge400_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/f119pw100_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/f404_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/olympus593_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/fd3sid_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/z33u2_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/bgw16_amp.dat'


data_file 'AUDIO_WAVEPACK' 'sfx/dlc_12vcummins'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_46fordmodular'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_53vortec'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_64powerstroke'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_488sound'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_apollosv8'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_argento'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ariant'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_avesvv12'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_b58b30'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_bmws702'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_brabus850'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_c6v8sound'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_c30a'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cw2019'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_demonv8'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_diablov12'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_elegyx'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_enginev10'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f40v8'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f50v12'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f136'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ferrarif12'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_gresleyh'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_gt3flat6'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_gtaspanov10'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_hemisound'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_k20a'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_laferrarisound'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lambov10'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lfasound'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_m113k'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_m158huayra'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_m297zonda'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_majimagt'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_mclarenv8'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_mercm177'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_mercm279'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_monroec'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_murciev12'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_musv8'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_nfsv8'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_p60b40'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_perfov10'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_porschema2'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_predatorv8'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_r34sound'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_rb26dett'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_roger'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_rotary7'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s85b50'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s85b50b'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_sentinelsg4'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_sestov10'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_shonen'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_skart'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_toysupmk4'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_trumpetzr'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_urusv8'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_v8sultanrs'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_venenov12'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_viperv10'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_zircoflow'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_genx'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_trent1000'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_trent1000tss'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cfm562c5'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_jt3d3b'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_jt3d7'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_jt3c'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cfm565'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_iaev2500'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cfmleap1a'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_pw1100g'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_jt8d'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cfm563b'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cfm567b'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cfmleap1b'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_pt6a67d'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ct79b'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_pw150a'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_pw127m'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_io540'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_io360'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lf507'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_trent500'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_pw2000'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_rb211535'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cf650c'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cf650e'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cf680c'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_trentxwb97'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_tf34ge100a'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_pw200'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ge400'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f119pw100'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f404'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_olympus593'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_genx2b'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ge90115b'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f20c'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_fd3sid'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s54b32'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_z33u2'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_bgw16'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_chevroletlt4'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_13b-rew'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_bmws55'
data_file 'AUDIO_WAVEPACK' 'sfx/resident'